"use client"

import { useState, useEffect } from "react"

interface BriefData {
  accountName: string
  includeClosedWon: boolean
  markdownReport: string
}

export default function HomePage() {
  const [accountName, setAccountName] = useState("")
  const [includeClosedWon, setIncludeClosedWon] = useState(true)
  const [isGenerating, setIsGenerating] = useState(false)
  const [progress, setProgress] = useState(0)
  const [briefData, setBriefData] = useState<BriefData | null>(null)
  const [copied, setCopied] = useState(false)
  const [accountNames, setAccountNames] = useState<string[]>([])
  const [isLoadingAccounts, setIsLoadingAccounts] = useState(true)

  // Load account names from CSV file
  useEffect(() => {
    const loadAccountNames = async () => {
      try {
        const response = await fetch('/data/mock_crm_hackathon.csv')
        const csvText = await response.text()
        
        // Parse CSV manually (simple parsing for semicolon-separated values)
        const lines = csvText.split('\n').filter(line => line.trim())
        const headers = lines[0].split(';')
        
        // Find the Account_Name column index
        const accountNameIndex = headers.findIndex(header => 
          header.trim().toLowerCase() === 'account_name'
        )
        
        if (accountNameIndex !== -1) {
          const accounts = lines
            .slice(1) // Skip header row
            .map(line => {
              const columns = line.split(';')
              return columns[accountNameIndex]?.trim()
            })
            .filter(name => name && name.length > 0)
            .filter((name, index, arr) => arr.indexOf(name) === index) // Remove duplicates
            .sort()
          
          setAccountNames(accounts)
        } else {
          throw new Error('Account_Name column not found')
        }
      } catch (error) {
        console.error('Error loading account names from CSV:', error)
        // Fallback to some default accounts
        setAccountNames(['Contoso Ltd.', 'Fabrikam AG', 'Adventure Works', 'Northwind Traders', 'Wide World Importers'])
      } finally {
        setIsLoadingAccounts(false)
      }
    }

    loadAccountNames()
  }, [])

  const generateDummyMarkdownReport = (accountName: string, includeClosedWon: boolean) => {
    const isContoso = accountName.toLowerCase().includes("contoso")

    if (isContoso) {
      return `# Account Brief for ${accountName}

## Account Snapshot – Status Quo & Financials

**Contoso Ltd.** is a global manufacturing leader specializing in IoT sensors with €2.8B revenue (2024). Recent expansion into AI R&D with new Munich hub signals strategic pivot toward intelligent manufacturing. Strong financial position with 15% YoY growth in industrial automation segment.

### Key Financial Metrics
- **Revenue:** €2.8B (2024)
- **Growth Rate:** 15% YoY
- **Focus Area:** Industrial automation and IoT

---

## Previous Deals & Installed Base

${includeClosedWon 
  ? `Previous Microsoft wins include **Azure IoT Suite** (€2.6M, Feb 2024) and **Power BI Premium** (€0.9M, Nov 2023). Installed base demonstrates commitment to Microsoft cloud ecosystem with focus on data analytics and IoT infrastructure.

### Recent Wins
- **Azure IoT Suite**: €2.6M (February 2024)
- **Power BI Premium**: €0.9M (November 2023)

### Technology Stack
- Microsoft Azure Cloud Platform
- Power BI Analytics
- IoT Infrastructure`
  : `No closed/won analysis included in this brief.`}

---

## Low-ACR Pipeline Deals

Two qualified deals with low ACR scores:

### Current Deals
- **Azure OpenAI** (DEAL-317, ACR: 0.12, Owner: Tobi)
- **Microsoft Fabric** (DEAL-322, ACR: 0.18, Owner: Max)

Both deals align with Contoso's AI transformation initiative announced in recent news.

---

## Upsell Synergies with High Potential

### Highest synergy potential:

1. **Azure OpenAI + Azure IoT Suite** 
   - **Fit Score:** 0.8
   - **Use Case:** Enable predictive maintenance with AI-powered insights

2. **Microsoft Fabric + Power BI Premium**
   - **Fit Score:** 0.75  
   - **Use Case:** Unified analytics platform for manufacturing data

> **Combined upsell potential:** €4.2M based on similar manufacturing accounts.

---

## 🎯 Ready-to-Send Storyline

Position Contoso's AI R&D expansion as the perfect catalyst for **Azure OpenAI** integration with their existing **Azure IoT Suite**. 

The Munich hub announcement proves executive commitment to AI transformation, making this the ideal time to propose **Microsoft Fabric** as the unified data foundation that extends their successful **Power BI Premium** deployment.

### Key Talking Points
- Leverage existing Azure investment
- AI-driven manufacturing insights
- Unified data platform strategy
- Proven ROI from current Microsoft solutions

---

*Generated by SELLY • More insights. More sales.*`
    } else {
      return `# Account Brief for ${accountName}

## Account Snapshot – Status Quo & Financials

**${accountName}** is a mid-market enterprise with strong growth trajectory. Recent market activities suggest expansion into new technology areas with focus on digital transformation initiatives.

---

## Previous Deals & Installed Base

${includeClosedWon 
  ? `Limited previous Microsoft engagement. Deal to establish strategic partnership with initial cloud adoption wins.

### Deal Areas
- Cloud infrastructure adoption
- Productivity solutions
- Data analytics platform`
  : `No closed/won analysis included in this brief.`}

---

## Low-ACR Pipeline Deals

Potential deals identified based on industry trends and company profile. Recommend discovery calls to uncover specific business challenges and technology gaps.

### Recommended Discovery Areas
- Current technology stack assessment
- Digital transformation roadmap
- Budget and timeline evaluation

---

## Upsell Synergies with High Potential

### Recommended approach:

1. **Start with foundational cloud services**
2. **Build toward integrated Microsoft ecosystem**
3. **Focus on business value and ROI demonstration**

> **Estimated deal size:** €1-3M based on company profile.

---

## 🎯 Ready-to-Send Storyline

Position Microsoft as the strategic technology partner for ${accountName}'s digital transformation journey. Focus on proven ROI and seamless integration capabilities to build long-term enterprise relationship.

### Key Strategy
- Establish foundational partnership
- Demonstrate quick wins
- Build toward comprehensive solution

---

*Generated by SELLY • More insights. More sales.*`
    }
  }

  const handleGenerate = async () => {
    if (!accountName.trim()) return

    setIsGenerating(true)
    setProgress(0)
    setBriefData(null)

    // Simulate analysis workflow with progress updates
    const steps = [
      { name: "Data Collection", duration: 1200 }, // 35% 
      { name: "Analysis", duration: 1200 }, // 70%
      { name: "Report Generation", duration: 800 }, // 100%
    ]

    let currentProgress = 0
    for (let i = 0; i < steps.length; i++) {
      await new Promise((resolve) => setTimeout(resolve, steps[i].duration))
      currentProgress = ((i + 1) / steps.length) * 100
      setProgress(currentProgress)
    }

    // Generate dummy markdown report (later this will be replaced with LLM agent)
    const markdownReport = generateDummyMarkdownReport(accountName, includeClosedWon)
    setBriefData({
      accountName,
      includeClosedWon,
      markdownReport,
    })

    setIsGenerating(false)
    setProgress(0)
  }

  const handleCopy = async () => {
    if (!briefData) return

    try {
      await navigator.clipboard.writeText(briefData.markdownReport)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.error("Copy failed:", err)
    }
  }

  const handleDownload = () => {
    if (!briefData) return

    const blob = new Blob([briefData.markdownReport], { type: "text/markdown" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `AccountBrief-${briefData.accountName.replace(/[^a-zA-Z0-9]/g, "-")}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const handleReset = () => {
    setAccountName("")
    setIncludeClosedWon(true)
    setBriefData(null)
    setCopied(false)
  }

  // Simple markdown to HTML converter
  const markdownToHtml = (markdown: string) => {
    let html = markdown
      // Headers
      .replace(/^# (.*$)/gim, '<h1 class="text-3xl font-bold text-gray-900 mb-4 pb-2 border-b border-gray-300">$1</h1>')
      .replace(/^## (.*$)/gim, '<h2 class="text-2xl font-semibold mb-3 mt-6" style="color: #0078D4;">$1</h2>')
      .replace(/^### (.*$)/gim, '<h3 class="text-xl font-medium text-gray-800 mb-2 mt-4">$1</h3>')
      // Bold text
      .replace(/\*\*(.*?)\*\*/g, '<strong class="font-semibold" style="color: #0078D4;">$1</strong>')
      // Italic text
      .replace(/\*(.*?)\*/g, '<em class="italic text-gray-600">$1</em>')
      // Horizontal rules
      .replace(/^---$/gim, '<hr class="my-6 border-gray-300" />')
      // Blockquotes
      .replace(/^> (.*$)/gim, '<blockquote class="border-l-4 pl-4 py-2 my-4 bg-blue-50 italic text-gray-700" style="border-left-color: #0078D4;">$1</blockquote>')
    
    // Handle lists
    const lines = html.split('\n')
    const processedLines = []
    let inList = false
    
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i]
      
      if (line.match(/^- /)) {
        if (!inList) {
          processedLines.push('<ul class="list-disc list-inside mb-3 text-gray-700">')
          inList = true
        }
        processedLines.push(`<li class="mb-1">${line.replace(/^- /, '')}</li>`)
      } else if (line.match(/^\d+\. /)) {
        if (!inList) {
          processedLines.push('<ol class="list-decimal list-inside mb-3 text-gray-700">')
          inList = true
        }
        processedLines.push(`<li class="mb-1">${line.replace(/^\d+\. /, '')}</li>`)
      } else {
        if (inList) {
          processedLines.push('</ul>')
          inList = false
        }
        processedLines.push(line)
      }
    }
    
    if (inList) {
      processedLines.push('</ul>')
    }
    
    return processedLines
      .join('<br/>')
      // Clean up extra br tags after headers and block elements
      .replace(/(<\/h[1-6]>)<br\/>/g, '$1')
      .replace(/(<\/blockquote>)<br\/>/g, '$1')
      .replace(/(<hr[^>]*>)<br\/>/g, '$1')
      .replace(/(<\/ul>)<br\/>/g, '$1')
      .replace(/(<\/ol>)<br\/>/g, '$1')
      .replace(/(<ul[^>]*>)<br\/>/g, '$1')
      .replace(/(<ol[^>]*>)<br\/>/g, '$1')
  }

  return (
    <div
      className="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100"
      style={{ fontFamily: "Segoe UI, system-ui, sans-serif" }}
    >
      <div className="max-w-6xl mx-auto px-6 py-20">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="flex items-center justify-center mb-4">
            <img 
              src="/img/logoimg.png" 
              alt="SELLY Logo" 
              className="w-12 h-12 mr-3"
            />
            <h1 className="text-4xl font-light text-gray-800">SELLY</h1>
          </div>
          <h2 className="text-xl text-gray-600 font-light mb-2">More insights. More sales.</h2>
          <p className="text-gray-500">Give enterprise sellers every critical insight about a target account in under ten seconds</p>
        </div>

        {/* Input Form */}
        <div className="bg-white rounded-lg shadow-lg border border-gray-200 p-8 mb-8" style={{ borderRadius: '8px' }}>
          <div className="mb-6">
            <h3 className="text-2xl font-light text-gray-800 mb-2">Generate Account Brief</h3>
            <p className="text-gray-600">Get snapshot, low-ACR pipeline, upsell synergies, and ready-to-send storyline</p>
          </div>

          <div className="space-y-6">
            {/* Account Name Dropdown */}
            <div>
              <label htmlFor="account-name" className="block text-sm font-semibold text-gray-700 mb-2">
                Account Name *
              </label>
              {isLoadingAccounts ? (
                <div className="w-full px-4 py-3 border border-gray-300 bg-gray-100 rounded flex items-center" 
                     style={{ borderRadius: '8px' }}>
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-gray-400 mr-2"></div>
                  <span className="text-gray-500">Loading accounts...</span>
                </div>
              ) : (
                <select
                  id="account-name"
                  value={accountName}
                  onChange={(e) => setAccountName(e.target.value)}
                  disabled={isGenerating}
                  className="w-full px-4 py-3 border border-gray-300 focus:ring-2 focus:border-blue-500 disabled:bg-gray-100 disabled:cursor-not-allowed bg-white"
                  style={{ borderRadius: '8px' }}
                >
                  <option value="">Select an account...</option>
                  {accountNames.map((name) => (
                    <option key={name} value={name}>
                      {name}
                    </option>
                  ))}
                </select>
              )}
            </div>

            {/* Checkbox */}
            <div className="flex items-center">
              <input
                id="include-closed-won"
                type="checkbox"
                checked={includeClosedWon}
                onChange={(e) => setIncludeClosedWon(e.target.checked)}
                disabled={isGenerating}
                className="h-4 w-4 focus:ring-2 border-gray-300 rounded disabled:cursor-not-allowed"
                style={{ accentColor: '#0078D4' }}
              />
              <label htmlFor="include-closed-won" className="ml-3 text-sm text-gray-700">
                Include closed/won analysis
              </label>
            </div>

            {/* Progress Bar */}
            {isGenerating && (
              <div>
                <div className="flex justify-between items-center mb-2">
                  <span className="text-sm text-gray-600">Generating brief...</span>
                  <span className="text-sm text-gray-600">{Math.round(progress)}%</span>
                </div>
                <div className="w-full bg-gray-200 rounded-full h-2">
                  <div
                    className="bg-blue-600 h-2 rounded-full transition-all duration-300"
                    style={{ width: `${progress}%` }}
                  />
                </div>
              </div>
            )}

            {/* Action Buttons */}
            <div className="flex gap-3">
              <button
                onClick={handleGenerate}
                disabled={!accountName.trim() || isGenerating}
                className="flex-1 hover:opacity-90 disabled:bg-gray-400 disabled:cursor-not-allowed text-white font-semibold py-4 px-6 transition-colors duration-200 flex items-center justify-center"
                style={{ backgroundColor: '#0078D4', borderRadius: '8px' }}
              >
                {isGenerating ? (
                  <>
                    <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white mr-3" />
                    Generating Brief...
                  </>
                ) : (
                  <>
                    Generate Brief
                    <svg className="ml-2 h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                    </svg>
                  </>
                )}
              </button>
              
              {briefData && (
                <button
                  onClick={handleReset}
                  className="px-6 py-4 border border-gray-300 rounded-md hover:bg-gray-50 transition-colors text-gray-700"
                  style={{ borderRadius: '8px' }}
                >
                  New Brief
                </button>
              )}
            </div>
          </div>
        </div>

        {/* Brief Results */}
        {briefData && (
          <div className="bg-white rounded-lg shadow-lg border border-gray-200 p-8" style={{ borderRadius: '8px' }}>
            {/* Brief Header with Actions */}
            <div className="flex justify-between items-center mb-8">
              <div className="flex items-center">
                <img 
                  src="/img/logoimg.png" 
                  alt="SELLY Logo" 
                  className="w-10 h-10 mr-4"
                />
                <div>
                  <h2 className="text-3xl font-light text-gray-800">Account Brief Generated</h2>
                  <p className="text-gray-600">Critical insights for your target account</p>
                </div>
              </div>

              <div className="flex gap-3">
                <button
                  onClick={handleCopy}
                  className="flex items-center px-4 py-2 border border-gray-300 rounded-md hover:bg-gray-50 transition-colors"
                >
                  {copied ? (
                    <>
                      <svg className="w-4 h-4 mr-2 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                      </svg>
                      Copied!
                    </>
                  ) : (
                    <>
                      <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth={2}
                          d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                        />
                      </svg>
                      Copy Brief
                    </>
                  )}
                </button>
                <button
                  onClick={handleDownload}
                  className="flex items-center px-4 py-2 border border-gray-300 rounded-md hover:bg-gray-50 transition-colors"
                  style={{ borderRadius: '8px' }}
                >
                  <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
                    />
                  </svg>
                  Download Brief
                </button>
              </div>
            </div>

            {/* Account Brief Display */}
            <div className="border border-gray-200 rounded-lg p-6 bg-gray-50" style={{ borderRadius: '8px' }}>
              <div className="prose prose-gray max-w-none">
                <div 
                  className="text-gray-800 leading-relaxed"
                  dangerouslySetInnerHTML={{ __html: markdownToHtml(briefData.markdownReport) }}
                />
              </div>
            </div>
          </div>
        )}

        {/* Footer */}
        <div className="mt-8 text-center bg-white/60 backdrop-blur-sm rounded-lg border border-gray-200 p-4" style={{ borderRadius: '8px' }}>
          <p className="text-sm text-gray-500 mb-1">Powered by SELLY AI</p>
          <p className="text-xs text-gray-400">More insights. More sales.</p>
        </div>
      </div>
    </div>
  )
}
